angular.module('app')
.controller('PostsCtrl', function ($scope, PostsSvc) {
  $scope.addPost = function () {
    if ($scope.postfileRef) {
      PostsSvc.create({
        username: 'miketest',
        fileRef: $scope.postfileRef,
        prefix: $scope.postprefix,
        firstName: $scope.postfirstName,
        lastName: $scope.postlastName,
        address: $scope.postaddress,
        townland: $scope.posttownland,
        phone: $scope.postphone,
        fax: $scope.postfax,
        email: $scope.postemail,
        noResidents: $scope.postnoResidents,  
        noDoubleBeds: $scope.postnoDoubleBeds,
        noSingleBeds: $scope.postnoSingleBeds,
        waterSupply: $scope.postwaterSupply,

        soilType:    $scope.soilType,
        aquifer:     $scope.aquifer,
        vulnerability:    $scope.vulnerability,
        bedrockType:     $scope.bedrockType,
        waterScheme:    $scope.waterScheme,
        gwProtection:     $scope.gwProtection,
        sourceProtection:      $scope.sourceProtection,
        gwResponse:      $scope.gwResponse,
        sigSites:      $scope.sigSites,
        pastExp:  $scope.pastExp,
        comments1: $scope.comments1,
        //3.1 Visual Assessment
        landscapePos:    $scope.landscapePos,
        slope:     $scope.slope,
        houses:    $scope.houses,
        existingLandUse:     $scope.existingLandUse,
        vegitation:    $scope.vegitation,
        gwFlow:     $scope.gwFlow,
        groundCond:    $scope.groundCond,
        siteBound:     $scope.siteBound,
        roads:      $scope.roads,
        outcrops:      $scope.outcrops,
        ponding:      $scope.ponding,
        lakes:  $scope.lakes,
        beaches: $scope.beaches,
        wetlands: $scope.wetlands,
        karst:  $scope.karst,
        watercourse: $scope.watercourse,
        springs: $scope.springs,
        comments2:  $scope.comments2,
        //3.2 Trial hole evaluation
        comments3:    $scope.comments3,
        //3.3 Pre soak t-test
        test1date:     $scope.test1date,
        test1time:    $scope.test1time,
        test2date:     $scope.test2date,
        test2time:    $scope.test2time,
        test3date:     $scope.test3date,
        test3time:    $scope.test3time,
        //3.4 Percolation p-test
        test111:     $scope.test111,
        test112:    $scope.test112,
        avg111:    $scope.avg111,
        test121:     $scope.test121,
        test122:    $scope.test122,
        avg121:    $scope.avg121,
        test131:     $scope.test131,
        test132:    $scope.test132,
        avg131:    $scope.avg131,
        test211:     $scope.test211,
        test212:    $scope.test212,
        avg211:    $scope.avg211,
        test221:     $scope.test221,
        test222:    $scope.test222,
        avg221:    $scope.avg221,
        test231:     $scope.test231,
        test232:    $scope.test232,
        avg231:    $scope.avg231,
        test311:     $scope.test311,
        test312:    $scope.test312,
        avg311:    $scope.avg311,
        test321:     $scope.test321,
        test322:    $scope.test322,
        avg321:    $scope.avg321,
        test331:     $scope.test331,
        test332:    $scope.test332,
        avg331:    $scope.avg331,
        comments4:    $scope.comments4,
        //3,5 Pre soak p-test
        ptest1date:     $scope.ptest1date,
        ptest1time:    $scope.ptest1time,
        ptest2date:     $scope.ptest2date,
        ptest2time:    $scope.ptest2time,
        ptest3date:     $scope.ptest3date,
        ptest3time:    $scope.ptest3time,
        //3.6 Percolation p-test
        ptest111:     $scope.ptest111,
        ptest112:    $scope.ptest112,
        pavg111:    $scope.pavg111,
        ptest121:     $scope.ptest121,
        ptest122:    $scope.ptest122,
        pavg121:    $scope.pavg121,
        ptest131:     $scope.ptest131,
        ptest132:    $scope.ptest132,
        pavg131:    $scope.pavg131,
        ptest211:     $scope.ptest211,
        ptest212:    $scope.ptest212,
        pavg211:    $scope.pavg211,
        ptest221:     $scope.ptest221,
        ptest222:    $scope.ptest222,
        pavg221:    $scope.pavg221,
        ptest231:     $scope.ptest231,
        ptest232:    $scope.ptest232,
        pavg231:    $scope.pavg231,
        ptest311:     $scope.ptest311,
        ptest312:    $scope.ptest312,
        pavg311:    $scope.pavg311,
        ptest321:     $scope.ptest321,
        ptest322:    $scope.ptest322,
        pavg321:    $scope.pavg321,
        ptest331:     $scope.ptest331,
        ptest332:    $scope.ptest332,
        pavg331:    $scope.pavg331,
        comments5:    $scope.comments5,
        //4.0 Conclusions
        suitableFor:     $scope.suitableFor,
        secondaryTreat:    $scope.secondaryTreat,
        //5.0 Reccomendations
        propInstall:     $scope.propInstall,
        dischargeTo:    $scope.dischargeTo,
        trenchInv:    $scope.trenchInv,
        //6,0 Treatment system details
        propInstallTank:    $scope.propInstallTank,
        dischargeToTank:    $scope.dischargeToTank,
        trenchInvTank:    $scope.trenchInvTank,
        noTrenches:     $scope.noTrenches,
        lengthTrenches:    $scope.lengthTrenches,
        invLvlTrench:    $scope.invLvlTrench,
        moundnoTrenches:     $scope.moundnoTrenches,
        moundlengthTrenches:    $scope.moundlengthTrenches,
        moundinvLvlTrench:    $scope.moundinvLvlTrench,
        //7.0 Site assessor details
        company:     $scope.company,
        experience:    $scope.experience,
        insurance:    $scope.insurance
      })

      .success(function (post) {
        $scope.posts.unshift(post)
        $scope.postfileRef = null,
        $scope.postprefix = null,
        $scope.postfirstName = null,
        $scope.postlastName = null,
        $scope.postaddress = null,
        $scope.posttownland = null,
        $scope.postphone = null,
        $scope.postfax = null,
        $scope.postemail = null,
        $scope.postnoResidents = null,
        $scope.postnoDoubleBeds = null,
        $scope.postnoSingleBeds = null,
        $scope.postwaterSupply = null,

        $scope.soilType = null,
        $scope.aquifer = null,
        $scope.vulnerability = null,
        $scope.bedrockType = null,
        $scope.waterScheme = null,
        $scope.gwProtection = null,
        $scope.sourceProtection = null,
        $scope.gwResponse = null,
        $scope.sigSites = null,
        $scope.pastExp = null,
        $scope.comments1 = null,
        //3.1 Visual Assessment
        $scope.landscapePos = null,
        $scope.slope = null,
        $scope.houses = null,
        $scope.existingLandUse = null,
        $scope.vegitation = null,
        $scope.gwFlow = null,
        $scope.groundCond = null,
        $scope.siteBound = null,
        $scope.roads = null,
        $scope.outcrops = null,
        $scope.ponding = null,
        $scope.lakes = null,
        $scope.beaches = null,
        $scope.wetlands = null,
        $scope.karst = null,
        $scope.watercourse = null,
        $scope.springs = null,
        $scope.comments2 = null,
        //3.2 Trial hole evaluation
        $scope.comments3 = null,
        //3.3 Pre soak t-test
        $scope.test1date = null,
        $scope.test1time = null,
        $scope.test2date = null,
        $scope.test2time = null,
        $scope.test3date = null,
        $scope.test3time = null,
        //3.4 Percolation p-test
        $scope.test111 = null,
        $scope.test112 = null,
        $scope.avg111 = null,
        $scope.test121 = null,
        $scope.test122 = null,
        $scope.avg121 = null,
        $scope.test131 = null,
        $scope.test132 = null,
        $scope.avg131 = null,
        $scope.test211 = null,
        $scope.test212 = null,
        $scope.avg211 = null,
        $scope.test221 = null,
        $scope.test222 = null,
        $scope.avg221 = null,
        $scope.test231 = null,
        $scope.test232 = null,
        $scope.avg231 = null,
        $scope.test311 = null,
        $scope.test312 = null,
        $scope.avg311 = null,
        $scope.test321 = null,
        $scope.test322 = null,
        $scope.avg321 = null,
        $scope.test331 = null,
        $scope.test332 = null,
        $scope.avg331 = null,
        $scope.comments4 = null,
        //3,5 Pre soak p-test
        $scope.ptest1date = null,
        $scope.ptest1time = null,
        $scope.ptest2date = null,
        $scope.ptest2time = null,
        $scope.ptest3date = null,
        $scope.ptest3time = null,
        //3.6 Percolation p-test
        $scope.ptest111 = null,
        $scope.ptest112 = null,
        $scope.pavg111 = null,
        $scope.ptest121 = null,
        $scope.ptest122 = null,
        $scope.pavg121 = null,
        $scope.ptest131 = null,
        $scope.ptest132 = null,
        $scope.pavg131 = null,
        $scope.ptest211 = null,
        $scope.ptest212 = null,
        $scope.pavg211 = null,
        $scope.ptest221 = null,
        $scope.ptest222 = null,
        $scope.pavg221 = null,
        $scope.ptest231 = null,
        $scope.ptest232 = null,
        $scope.pavg231 = null,
        $scope.ptest311 = null,
        $scope.ptest312 = null,
        $scope.pavg311 = null,
        $scope.ptest321 = null,
        $scope.ptest322 = null,
        $scope.pavg321 = null,
        $scope.ptest331 = null,
        $scope.ptest332 = null,
        $scope.pavg331 = null,
        $scope.comments5 = null,
        //4.0 Conclusions
        $scope.suitableFor = null,
        $scope.secondaryTreat = null,
        //5.0 Reccomendations
        $scope.propInstall = null,
        $scope.dischargeTo = null,
        $scope.trenchInv = null,
        //6,0 Treatment system details
        $scope.propInstallTank = null,
        $scope.dischargeToTank = null,
        $scope.trenchInvTank = null,
        $scope.noTrenches = null,
        $scope.lengthTrenches = null,
        $scope.invLvlTrench = null,
        $scope.moundnoTrenches = null,
        $scope.moundlengthTrenches = null,
        $scope.moundinvLvlTrench = null,
        //7.0 Site assessor details
        $scope.company = null,
        $scope.experience = null,
        $scope.insurance = null
      })
    }
  }

  PostsSvc.fetch()
  .success(function (posts) {
    $scope.posts = posts
  })
})
