var db = require('../db')
var Post = db.model('Post', {
  	username: { type: String, required: true },
  	fileRef: 		{ type: String, required: true },
	prefix: 		{ type: String, required: true },
	firstName: 		{ type: String, required: true },
	lastName: 		{ type: String, required: true },
	address: 		{ type: String, required: true },
	townland: 		{ type: String, required: true },
	phone: 			{ type: String, required: true },
	fax: 			{ type: String, required: true },
	email: 			{ type: String, required: true },
	noResidents: 	{ type: String, required: true },
	noDoubleBeds: 	{ type: String, required: true },
	noSingleBeds: 	{ type: String, required: true },
	waterSupply: 	{ type: String, required: true },
	//2.0 general Details
    soilType:    { type: String, required: true },
    aquifer:     { type: String, required: true },
    vulnerability:    { type: String, required: true },
    bedrockType:     { type: String, required: true },
    waterScheme:    { type: String, required: true },
    gwProtection:     { type: String, required: true },
    sourceProtection:      { type: String, required: true },
    gwResponse:      { type: String, required: true },
    sigSites:      { type: String, required: true },
    pastExp:  { type: String, required: true },
    comments1: { type: String, required: true },
    //3.1 Visual Assessment
    landscapePos:    { type: String, required: true },
    slope:     { type: String, required: true },
    houses:    { type: String, required: true },
    existingLandUse:     { type: String, required: true },
    vegitation:    { type: String, required: true },
    gwFlow:     { type: String, required: true },
    groundCond:    { type: String, required: true },
    siteBound:     { type: String, required: true },
    roads:      { type: String, required: true },
    outcrops:      { type: String, required: true },
    ponding:      { type: String, required: true },
    lakes:  { type: String, required: true },
    beaches: { type: String, required: true },
    wetlands: { type: String, required: true },
    karst:  { type: String, required: true },
    watercourse: { type: String, required: true },
    springs: { type: String, required: true },
    comments2:  { type: String, required: true },
    //3.2 Trial hole evaluation
    comments3:    { type: String, required: true },
    //3.3 Pre soak t-test
    test1date:     { type: String, required: true },
    test1time:    { type: String, required: true },
    test2date:     { type: String, required: true },
    test2time:    { type: String, required: true },
    test3date:     { type: String, required: true },
    test3time:    { type: String, required: true },
    //3.4 Percolation p-test
    test111:     { type: String, required: true },
    test112:    { type: String, required: true },
    avg111:    { type: String, required: true },
    test121:     { type: String, required: true },
    test122:    { type: String, required: true },
    avg121:    { type: String, required: true },
    test131:     { type: String, required: true },
    test132:    { type: String, required: true },
    avg131:    { type: String, required: true },
    test211:     { type: String, required: true },
    test212:    { type: String, required: true },
    avg211:    { type: String, required: true },
    test221:     { type: String, required: true },
    test222:    { type: String, required: true },
    avg221:    { type: String, required: true },
    test231:     { type: String, required: true },
    test232:    { type: String, required: true },
    avg231:    { type: String, required: true },
    test311:     { type: String, required: true },
    test312:    { type: String, required: true },
    avg311:    { type: String, required: true },
    test321:     { type: String, required: true },
    test322:    { type: String, required: true },
    avg321:    { type: String, required: true },
    test331:     { type: String, required: true },
    test332:    { type: String, required: true },
    avg331:    { type: String, required: true },
    comments4:    { type: String, required: true },
    //3,5 Pre soak p-test
    ptest1date:     { type: String, required: true },
    ptest1time:    { type: String, required: true },
    ptest2date:     { type: String, required: true },
    ptest2time:    { type: String, required: true },
    ptest3date:     { type: String, required: true },
    ptest3time:    { type: String, required: true },
    //3.6 Percolation p-test
    ptest111:     { type: String, required: true },
    ptest112:    { type: String, required: true },
    pavg111:    { type: String, required: true },
    ptest121:     { type: String, required: true },
    ptest122:    { type: String, required: true },
    pavg121:    { type: String, required: true },
    ptest131:     { type: String, required: true },
    ptest132:    { type: String, required: true },
    pavg131:    { type: String, required: true },
    ptest211:     { type: String, required: true },
    ptest212:    { type: String, required: true },
    pavg211:    { type: String, required: true },
    ptest221:     { type: String, required: true },
    ptest222:    { type: String, required: true },
    pavg221:    { type: String, required: true },
    ptest231:     { type: String, required: true },
    ptest232:    { type: String, required: true },
    pavg231:    { type: String, required: true },
    ptest311:     { type: String, required: true },
    ptest312:    { type: String, required: true },
    pavg311:    { type: String, required: true },
    ptest321:     { type: String, required: true },
    ptest322:    { type: String, required: true },
    pavg321:    { type: String, required: true },
    ptest331:     { type: String, required: true },
    ptest332:    { type: String, required: true },
    pavg331:    { type: String, required: true },
    comments5:    { type: String, required: true },
    //4.0 Conclusions
    suitableFor:     { type: String, required: true },
    secondaryTreat:    { type: String, required: true },
    //5.0 Reccomendations
    propInstall:     { type: String, required: true },
    dischargeTo:    { type: String, required: true },
    trenchInv:    { type: String, required: true },
    //6,0 Treatment system details
    propInstallTank:    { type: String, required: true },
    dischargeToTank:    { type: String, required: true },
    trenchInvTank:    { type: String, required: true },
    noTrenches:     { type: String, required: true },
    lengthTrenches:    { type: String, required: true },
    invLvlTrench:    { type: String, required: true },
    moundnoTrenches:     { type: String, required: true },
    moundlengthTrenches:    { type: String, required: true },
    moundinvLvlTrench:    { type: String, required: true },
    //7.0 Site assessor details
    company:     { type: String, required: true },
    experience:    { type: String, required: true },
    insurance:    { type: String, required: true },
  	date:     { type: Date,   required: true, default: Date.now }
})

module.exports = Post